server:
  port: 8082
  servlet:
    context-path: /pagamento
    
spring:
  application:
    name: pagamento
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
#     dialect: org.hibernate.dialect.MySQL5InnoDBDialect  
  jmx:
    enabled: false
  datasource:
   url: jdbc:postgresql://localhost:5432/udemyProduto
   username: postgres
   password: 1234


  rabbitmq:
    host: localhost 
    port: 5672
    username: guest
    password: guest
        
crud:
  rabbitmq:
    exchange: crud.exchange
    queue: crud.produto.queue          

security:
  jwt:
    token: 
      secret-key: chave_microservices
      
eureka:
  instance: 
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka